# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xPDCsup0W3LjE4XGaH920Hl8vN2rHBK
"""

import random
from collections import deque

#Clase Proceso (igual que antes, pero la mejoro un poco)
class Proceso:
    def __init__(self, pid, nombre, burst, prioridad, llegada=0):
        self.pid = pid
        self.nombre = nombre
        self.burst = burst
        self.prioridad = prioridad
        self.llegada = llegada
        self.restante = burst
        self.estado = "NUEVO"
        self.t_bloqueado = 0
        self.inicio_ejecucion = None
        self.fin = None
        self.t_espera = 0

    def __str__(self):
        return f"{self.nombre} ({self.estado})"

#Clase Scheduler (Planificador) con más algoritmos
class Scheduler:
    def __init__(self, algoritmo, quantum=2):
        self.algoritmo = algoritmo
        self.quantum = quantum
        self.ready = deque()
        self.bloqueados = []
        self.procesos = []
        self.tiempo = 0
        self.contador_quantum = 0

    def agregar_proceso(self, proceso):
        """Añade un proceso nuevo al sistema."""
        proceso.estado = "LISTO"
        self.ready.append(proceso)
        self.procesos.append(proceso)
        print(f"  T={self.tiempo}: {proceso.nombre} pasa a LISTO")

    def seleccionar_proceso(self):
        """Elige el siguiente proceso a ejecutar según el algoritmo."""
        if not self.ready:
            return None

        if self.algoritmo == "FIFO":
            return self.ready[0]
        elif self.algoritmo == "SJF":
            return min(self.ready, key=lambda p: p.burst)
        elif self.algoritmo == "PRIORIDAD":
            return min(self.ready, key=lambda p: p.prioridad)
        elif self.algoritmo == "RR":
            return self.ready[0]
        else:
            return None

    def ejecutar_unidad(self, proceso_en_ejecucion):
        """Simula una unidad de tiempo."""
        # Actualizar procesos bloqueados
        for p in self.bloqueados[:]:
            p.t_bloqueado -= 1
            if p.t_bloqueado <= 0:
                p.estado = "LISTO"
                self.ready.append(p)
                self.bloqueados.remove(p)
                print(f"  T={self.tiempo}: {p.nombre} despierta y pasa a LISTO")

        # Si no hay proceso en ejecución, elegir uno
        if proceso_en_ejecucion is None and self.ready:
            proceso_en_ejecucion = self.seleccionar_proceso()
            if proceso_en_ejecucion:
                self.ready.remove(proceso_en_ejecucion)
                proceso_en_ejecucion.estado = "EJECUCION"
                if proceso_en_ejecucion.inicio_ejecucion is None:
                    proceso_en_ejecucion.inicio_ejecucion = self.tiempo
                    print(f"  T={self.tiempo}: {proceso_en_ejecucion.nombre} COMIENZA a ejecutarse")
                else:
                    print(f"  T={self.tiempo}: {proceso_en_ejecucion.nombre} REANUDA ejecución")

        # Ejecutar la unidad de tiempo para el proceso actual
        if proceso_en_ejecucion:
            proceso_en_ejecucion.restante -= 1
            self.contador_quantum += 1
            print(f"  T={self.tiempo}: Ejecutando {proceso_en_ejecucion.nombre} (restante: {proceso_en_ejecucion.restante})")

            # ¿El proceso terminó?
            if proceso_en_ejecucion.restante <= 0:
                proceso_en_ejecucion.estado = "TERMINADO"
                proceso_en_ejecucion.fin = self.tiempo + 1
                print(f"  T={self.tiempo}: **** {proceso_en_ejecucion.nombre} TERMINÓ ****")
                self.contador_quantum = 0
                return None

            # Simular un posible bloqueo (I/O)
            if random.random() < 0.15:
                proceso_en_ejecucion.estado = "BLOQUEADO"
                proceso_en_ejecucion.t_bloqueado = random.randint(2, 4)
                self.bloqueados.append(proceso_en_ejecucion)
                print(f"  T={self.tiempo}: --- {proceso_en_ejecucion.nombre} se BLOQUEA por {proceso_en_ejecucion.t_bloqueado} unidades ---")
                self.contador_quantum = 0
                return None

            # Verificar expropiación por PRIORIDAD
            if self.algoritmo == "PRIORIDAD" and self.ready:
                mejor_prioridad_listo = min(self.ready, key=lambda p: p.prioridad).prioridad
                if mejor_prioridad_listo < proceso_en_ejecucion.prioridad:
                    proceso_en_ejecucion.estado = "LISTO"
                    self.ready.append(proceso_en_ejecucion)
                    print(f"  T={self.tiempo}: >>> {proceso_en_ejecucion.nombre} INTERRUMPIDO por proceso de mayor prioridad <<<")
                    self.contador_quantum = 0
                    return None

            # 3d. Verificar fin de QUANTUM para Round Robin
            if self.algoritmo == "RR" and self.contador_quantum >= self.quantum:
                proceso_en_ejecucion.estado = "LISTO"
                self.ready.append(proceso_en_ejecucion)
                print(f"  T={self.tiempo}: --- {proceso_en_ejecucion.nombre} agota su QUANTUM y vuelve a LISTO ---")
                self.contador_quantum = 0
                return None

        # Incrementar tiempo de espera para los procesos en LISTO
        for p in self.ready:
            p.t_espera += 1

        return proceso_en_ejecucion

    def simular(self, tiempo_maximo=30):
        """Bucle principal de la simulación."""
        proceso_actual = None
        print(f"--- INICIO SIMULACIÓN ({self.algoritmo}) ---")
        while self.tiempo < tiempo_maximo:
            print(f"\n>>> Tiempo: {self.tiempo} <<<")
            proceso_actual = self.ejecutar_unidad(proceso_actual)


            for p in self.procesos:
                print(f"    {p.nombre}: {p.estado}")
            print(f"    Cola Listos: {[p.nombre for p in self.ready]}")
            print(f"    Bloqueados: {[p.nombre for p in self.bloqueados]}")

            self.tiempo += 1

        print("\n--- FIN DE LA SIMULACIÓN ---")
        self.mostrar_estadisticas()

    def mostrar_estadisticas(self):
        """Muestra las estadísticas finales."""
        print("\n=== ESTADÍSTICAS FINALES ===")
        for p in self.procesos:
            if p.fin:
                retorno = p.fin - p.llegada
                respuesta = p.inicio_ejecucion - p.llegada if p.inicio_ejecucion is not None else 'N/A'
                print(f"{p.nombre}: Llegada={p.llegada}, Retorno={retorno}, Espera={p.t_espera}, Respuesta={respuesta}")
            else:
                print(f"{p.nombre}: NO TERMINÓ")

# Crear procesos de ejemplo para SIGET
procesos_ejemplo = [
    Proceso(1, "Rutina_Calles", burst=8, prioridad=5, llegada=0),
    Proceso(2, "Emergencia_Accidente", burst=3, prioridad=1, llegada=2),
    Proceso(3, "Mantenimiento_BD", burst=6, prioridad=3, llegada=1),
    Proceso(4, "Alerta_Sensor", burst=2, prioridad=1, llegada=4)
]

# EJECUTAR SIMULACIÓN CON FIFO
print("\n\n" + "="*50)
print("SIMULACIÓN CON ALGORITMO FIFO")
print("="*50)
sched_fifo = Scheduler("FIFO")
for p in procesos_ejemplo:
    sched_fifo.agregar_proceso(p)
sched_fifo.simular(25)

# EJECUTAR SIMULACIÓN CON PRIORIDAD (EXPULSIVO)
print("\n\n" + "="*50)
print("SIMULACIÓN CON ALGORITMO PRIORIDAD")
print("="*50)
procesos_ejemplo = [
    Proceso(1, "Rutina_Calles", burst=8, prioridad=5, llegada=0),
    Proceso(2, "Emergencia_Accidente", burst=3, prioridad=1, llegada=2),
    Proceso(3, "Mantenimiento_BD", burst=6, prioridad=3, llegada=1),
    Proceso(4, "Alerta_Sensor", burst=2, prioridad=1, llegada=4)
]
sched_prio = Scheduler("PRIORIDAD")
for p in procesos_ejemplo:
    sched_prio.agregar_proceso(p)
sched_prio.simular(25)

# EJECUTAR SIMULACIÓN CON ROUND ROBIN
print("\n\n" + "="*50)
print("SIMULACIÓN CON ALGORITMO ROUND ROBIN (Quantum=2)")
print("="*50)
procesos_ejemplo = [
    Proceso(1, "Rutina_Calles", burst=8, prioridad=5, llegada=0),
    Proceso(2, "Emergencia_Accidente", burst=3, prioridad=1, llegada=2),
    Proceso(3, "Mantenimiento_BD", burst=6, prioridad=3, llegada=1),
    Proceso(4, "Alerta_Sensor", burst=2, prioridad=1, llegada=4)
]
sched_rr = Scheduler("RR", quantum=2)
for p in procesos_ejemplo:
    sched_rr.agregar_proceso(p)
sched_rr.simular(25)